---
title: "Compaion planting"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)
library(rvest)
library(tidyverse)
# devtools::install_github("mattflor/chorddiag")
library(chorddiag)

rm_cites <- function(x){
  gsub("\\[|\\]|[0-9]", "", x)
}

fix_tables <- function(tab){
  nms <- tab[1,]
  tab <- tab[-1,]
  names(tab) <- nms
  tab <- as_tibble(tab)
  tab <- mutate(tab, across(everything(), rm_cites))
  tab <- janitor::clean_names(tab)
  tab <- filter(tab, !grepl("Commmon name", common_name))
  mutate(tab, across(everything(), tolower))
}

url <- "https://en.wikipedia.org/wiki/List_of_companion_plants"
webpage <- read_html(url)

table <- webpage %>% 
  html_nodes("table") %>% 
  html_table(header=TRUE, fill = TRUE)
table[[7]] <- NULL
table[[6]] <- NULL

nms <- lapply(table, names)
names(table) <- tolower(unique(unlist(nms)))
table <- lapply(table, fix_tables)
```

This page is scraped from the [wikipedia entry on companion planting](https://en.wikipedia.org/wiki/List_of_companion_plants).  

## Some resources on companion planting
- [Bakkane (No)](http://bakkane.blogspot.com/2009/05/samplanting-i-kjkkenhagen.html)  
- [Grønne saker (No)](http://gronnesaker.blogspot.com/2010/04/samplanting-i-kjkkenhagen.html)  
- [wikipedia (Eng)](https://en.wikipedia.org/wiki/List_of_companion_plants)  


<!-- ```{r} switch to reactable-->
<!-- bind_rows(table, .id = "class") %>%  -->
<!--   filter(common_name != "Common name") %>%  -->
<!--   DT::datatable(filter = "top") -->
<!-- ``` -->

```{r}
library(chorddiag)

make_chord <- function(which, table, ...){
  cols <- c("helps", "helped_by", "attracts", "repels_distracts", "avoid")
  col_pal <- stats::setNames(
    viridis::viridis(length(cols)),
    gsub("_", " ", cols))
  
  tabl <- bind_rows(table, .id = "class") %>% 
    filter(common_name == which) %>% 
    pivot_longer(one_of(c(cols))) %>% 
    separate_rows(value, sep = ",") %>% 
    mutate(
      across(everything(), ~ str_remove_all(.x, "citation needed")),
      across(everything(), ~ gsub("-|^ ", "", .x)),
      across(everything(), ~ gsub(" |_", " ", .x)),
      across(everything(), ~ str_wrap(.x, 10))
    ) %>% 
    group_by(common_name, name, value) %>% 
    tally() %>% 
    ungroup() %>% 
    unique() %>% 
    filter(!is.na(value), 
           n != "",
           value != "") %>% 
    arrange(name, value)
  
  tab <- tabl %>% 
    pivot_wider(names_from = value,
                values_from = n, 
                values_fill = 0)
  tabm = t(as.matrix(tab[,c(-1, -2)]))
  
  nms <- list(rownames(tabm),
              tab$name)
  names(nms)[2] <- which
  dimnames(tabm) <- nms
  # browser()
  chorddiag(tabm, 
            type = "bipartite", 
            showTicks = FALSE, 
            groupColors = c(
              colorRampPalette(c("grey90", "grey10"))(nrow(tabm)), 
              unname(col_pal[match(nms[[2]], names(col_pal))])
            ),
            ...)
}
```

# Chord diagram of companion plants

Hover/click on the connections to see the entire labels, for the ones with quite long labels.

## Vegetables
```{r}
p <- table$vegetables %>% 
  pull(common_name) %>% 
  unique() %>% 
  lapply(make_chord, table = table)
```
```{r}
htmltools::tagList(p)
```

# Fruit
```{r}
p <- table$fruit %>% 
  pull(common_name) %>% 
  unique() %>% 
  lapply(make_chord, table = table)
```
```{r}
htmltools::tagList(p)
```

# Herbs
```{r}
p <- table$herbs %>% 
  pull(common_name) %>% 
  unique() %>% 
  lapply(make_chord, table = table)
```
```{r}
htmltools::tagList(p)
```

# Flowers
```{r}
p <- table$flowers %>% 
  pull(common_name) %>% 
  unique() %>% 
  lapply(make_chord, table = table)
```
```{r}
htmltools::tagList(p)
```

# Other
```{r}
p <- table$herbs %>% 
  pull(common_name) %>% 
  unique() %>% 
  lapply(make_chord, table = table)
```
```{r}
htmltools::tagList(p)
```
